# your domain
domain: localhost:8080

# database url
database_url: "host=localhost user=postgres password=mysecretpassword dbname=postgres port=5432 sslmode=disable"



# cloudflare api
cf_email: ""
cf_key: ""

# source definition file
source-files:
  # use local file
  - source.yaml
  # use web file
  - https://proxy.sqeven.me/seven/source.yaml